name: mskg_cpu
channels:
  - willyd
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.12.0=pyhd8ed1ab_0
  - aiohttp=3.7.4=py37hcc03f2d_0
  - astor=0.8.1=pyh9f0ad1d_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=3.0.1=py_1000
  - attrs=21.2.0=pyhd8ed1ab_0
  - blinker=1.4=py_1
  - brotlipy=0.7.0=py37hcc03f2d_1001
  - ca-certificates=2020.12.5=h5b45459_0
  - cachetools=4.2.2=pyhd8ed1ab_0
  - certifi=2020.12.5=py37h03978a9_1
  - cffi=1.14.5=py37hd8e9650_0
  - chardet=4.0.0=py37h03978a9_1
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.4.7=py37h20c650d_0
  - gast=0.3.3=py_0
  - google-auth=1.30.0=pyh44b312d_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpcio=1.37.1=py37h04d2302_0
  - h5py=2.10.0=nompi_py37he280515_106
  - hdf5=1.10.6=nompi_he0bbb20_101
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=4.0.1=py37h03978a9_0
  - intel-openmp=2021.2.0=h57928b3_616
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - libblas=3.9.0=9_mkl
  - libcblas=3.9.0=9_mkl
  - liblapack=3.9.0=9_mkl
  - libprotobuf=3.16.0=h7755175_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markdown=3.3.4=pyhd8ed1ab_0
  - mkl=2021.2.0=hb70f87d_389
  - msys2-conda-epoch=20160418=1
  - multidict=5.1.0=py37hcc03f2d_1
  - numpy=1.20.2=py37hcbcd69c_0
  - oauthlib=3.0.1=py_0
  - openssl=1.1.1k=h8ffe710_0
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - pip=21.1.1=pyhd8ed1ab_0
  - protobuf=3.16.0=py37hf2a7229_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pyjwt=2.1.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyreadline=2.1=py37h03978a9_1003
  - pysocks=1.7.1=py37h03978a9_3
  - python=3.7.10=h7840368_100_cpython
  - python_abi=3.7=1_cp37m
  - requests=2.25.1=pyhd3deb0d_0
  - requests-oauthlib=1.3.0=pyh9f0ad1d_0
  - rsa=4.7.2=pyh44b312d_0
  - scipy=1.6.3=py37h924764e_0
  - setuptools=49.6.0=py37h03978a9_3
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.35.5=h8ffe710_0
  - tbb=2021.2.0=h2d74725_0
  - tensorboard=2.4.1=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - tensorflow=2.3.0=mkl_py37h3bad0a6_0
  - tensorflow-base=2.3.0=eigen_py37h17acbac_0
  - tensorflow-estimator=2.4.0=pyh9656e83_0
  - termcolor=1.1.0=py_2
  - typing_extensions=3.7.4.3=py_0
  - urllib3=1.26.4=pyhd8ed1ab_0
  - vc=14.2=hb210afc_4
  - vs2015_runtime=14.28.29325=h5e1d092_4
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.36.2=pyhd3deb0d_0
  - win_inet_pton=1.1.0=py37h03978a9_2
  - wincertstore=0.2=py37h03978a9_1006
  - wrapt=1.12.1=py37hcc03f2d_3
  - yarl=1.6.3=py37hcc03f2d_1
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=vc14h1cdd9ab_1
  - pip:
    - altgraph==0.17
    - future==0.18.2
    - opencv-python==4.5.1.48
    - pefile==2019.4.18
    - pyinstaller==4.3
    - pyinstaller-hooks-contrib==2021.1
    - pysimplegui==4.40.0
    - pywin32-ctypes==0.2.0
    - typing-extensions==3.10.0.0